import 'package:flutter/material.dart';

class FoodBrain {
  bool filterSearch(String value, String criteria) {
    return value
        .toString()
        .toLowerCase()
        .trim()
        .contains(new RegExp(r'' + criteria.toLowerCase().trim() + ''));
  }

  Future<List<Food>> search(String search) async {
    await Future.delayed(Duration(seconds: 2));
    if (search == "empty") return [];
    if (search == "error") throw Error();
    if (search.length > 20) throw Error();

    //Initial List of Foods
    List filteredList = Food.foodnames;
    List newList = [];
    List listOfIndex = [];
    print(filteredList);

    //Filtering Occurs
    try {
      for (int i = 0; i < filteredList.length; i++) {
        if ((filterSearch(filteredList[i], search) == true)) {
          newList.add(filteredList[i]);
          listOfIndex.add(i);
        }
      }
    } catch (e) {
      print(e);
    }
    print(newList);
    return List.generate(newList.length, (int index) {
      return Food(
        newList[index].toString(),
      );
    });
//    newList = [];
  }
}

//import 'package:flutter/material.dart';

class Food {
  String name;
  Food(this.name);
  static List<String> foods = [
    'Biscuit',
    'Bread roll',
    'Bread, white',
    'Cake',
    'Cookie',
    'Donut',
    'Infant cereal, Cerelac',
    'Macaroni or spaghetti',
    'Maize, cracked, cooked',
    'Maize, dried, raw',
    'Maize, flour, dry',
    'Maize, green, cooked',
    'Maize, on the cob, immature',
    'Maize, yellow, flour',
    'Millet, bulrush',
    'Millet, finger, grain or flour',
    'Mixed porridge flour (maize and oil)',
    'Mixed porridge flour (no maize)',
    'Mixed porridge flour (with maize)',
    'Porridge, fermented',
    'Rice, flour, local',
    'Rice, fried and boiled',
    'Rice, white, grain, raw',
    'Semolina',
    'Sorghum',
    'Sorghum, flour',
    'Vermicelli, uncooked',
    'Wheat, flour, whole grain',
    'Wheat,dough, deep fried',
    'Wheat, flour, 72% extract',
    'Wheat, flour, maida',
    'Cake (home made)',
    'Chapati, dry Indian',
    'Chapati with oil',
    'Donut-African',
    'Maize and kidney bean dish',
    'Maize and sorgum ugali (stiff porridge)',
    'Maize porridge with margarine and sugar',
    'Maize porridge no sugar no milk',
    'Maize porridge with sugar',
    'Maize porridge with sugar and egg',
    'Maize porridge with sugar and milk',
    'Maize ugali (stiff porridge)',
    'Millet porridge with sugar',
    'Mix flour porridge with sugar',
    'Pancake',
    'Rice biriyani',
    'Rice boiled no Oil',
    'Rice boiled with Oil',
    'Rice bread',
    'Rice bun',
    'Rice and meat pillau',
    'Rice and mung dish with coconut milk',
    'Rice and mung dish no coconut milk',
    'Rice poridge with coconut no sugar',
    'Rice porridge with sugar',
    'Rice ugali (stiff porridge)',
    'Rice with coconut milk',
    'Rice with ground meat',
    'Sorgum and millet ugali (stiff porridge)',
    '511   Sorgum porridge with sugar',
    'Vermicelli - cooked',
    'Vermicelli with coconut milk and sugar',
    'Vermicell with oil and sugar',
    'Vermicelli with coconut milk and salt',
    'Wheat fritter, sweet',
    'Wheat porridge',
    'Banana, cooked',
    'Breadfruit, raw',
    'Cassava, dried',
    'Cassava, dried, flour',
    'Cassava, raw',
    'Cassava, spicy crisps or chips',
    'Edible starch, tapioca or corn',
    'Potato, crisps, plain, salted',
    'Potato, English, cooked',
    'Potato, raw, with skin',
    'Squash, fresh-AP',
    'Squash, fresh-EP',
    'Sweet potato, fresh-AP',
    'Sweet potato, fresh-EP',
    'Sweet potato, orange',
    'Taro, raw',
    'Yam, raw',
    'Banana porridge, plain',
    'Banana porridge with meat',
    'Banana porridge with fish',
    'Banana porridge with meat and spinach',
    'Banana with cashew nut',
    'Banana with coconut milk',
    'Banana with kidney beans',
    'Banana with meat',
    'Banana with meat and coconut milk',
    'Banana with meat, oil and vegetable',
    'Banana with oil (no meat )',
    'Banana, boiled',
    'Banana, fried',
    'Banana, roast',
    'Cassava porridge with sugar',
    'Cassava stiff porridge',
    'Cassava with coconut milk',
    'Cassava, boiled',
    'Cassava, fried',
    'Kachori (spicy potato balls)',
    'Potato chips, fried',
    'Potato relish with beef',
    'Potato relish with coconut milk',
    'Potato relish with oil',
    'Potato, boiled',
    'Roots and tubers mixed',
    'Sweet potato, boiled',
    'Sweet potato, fried',
    'Taro, cooked, without salt',
    'Almonds',
    'Bambara groundnut, fresh',
    'Bean, kidney, green, cooked',
    'Bean, mung, dry',
    'Bean, mung, raw',
    'Beans, kidney, mature, boiled without salt',
    'Beans, kidney, mature seeds, raw',
    'Cashewnut',
    'Chickpea',
    'Chickpea flour (besan)',
    'Cowpea, green, uncooked',
    'Cowpea, uncooked',
    'Hyancinth beans (dried)',
    'Hyacinth-beans, immature, raw',
    'Hyacinth-beans, immature, boiled without salt',
    'Lentil, cooked',
    'Lentil, whole',
    'Palm seed',
    'Groundnuts',
    'Peanut butter, smooth',
    'Pigeon peas, cooked',
    'Pigeon peas, green',
    'Pigeon peas, raw',
    'Pumpkin seed',
    'Sesame seed',
    'Soybean, yellow',
    'Sunflower seed',
    'Bambara nut relish with coconut milk',
    'Bhajia (chickpea flour fritters)',
    'Chick pea relish with coconut milk',
    'Cow pea (dry) relish without oil',
    'Cow pea (dry) relish with oil',
    'Cow pea (fresh) relish without oil',
    'Cow pea relish with coconut milk',
    'Kidney bean relish without oil',
    'Kidney bean relish with oil',
    'Kidney bean relish with coconut milk',
    'Mung bean (dry) relish with cocount milk',
    'Mung bean (dry, boiled)',
    'Pigeon pea (fresh, cooked)',
    'Pigeon pea relish with coconut milk',
    'Pigeon pea relish with oil',
    'Beef liver, raw',
    'Beef, boneless',
    'Beef, liver, cooked',
    'Beef, medium fat, cooked',
    'Beef, tripe',
    'Chicken liver',
    'Chicken, raw',
    'Egg yolk',
    'Egg, chicken',
    'Fish, dried, cod',
    'Fish, dried, fresh water',
    'Fish, fresh',
    'Fish, high fat',
    'Fish, raw',
    'Fish, sardines',
    'Fish, small, dried, fresh water',
    'Fish, small, fresh, fresh water',
    'Fish, smoked, dried-AP',
    'Fish, smoked, dried-EP',
    'Goat meat',
    'Mutton, meat',
    'Pork, medium fat, cooked',
    'Sausage',
    'Beef relish with coconut milk',
    'Beef relish without oil',
    'Beef relish with oil',
    'Beef, fried',
    'Beef, ground, relish',
    'Chicken, boiled or roasted',
    'Chicken relish without oil',
    'Chicken relish with coconut milk',
    'Chicken relish with oil',
    'Chicken, fried',
    'Egg boiled',
    'Egg, fried',
    'Fish, fresh, stew',
    'Fish relish without oil',
    'Fish relish with coconut milk',
    'Fish relish with oil',
    'Fish, fried',
    'Fish, fried, relish',
    'Liver relish',
    'Liver, fried',
    'Meat samosa',
    'Meat, barbecued',
    'Omelet, spanish',
    'Omelet, spanish with potato',
    'Small dried fish relish with coconut milk ',
    'Small dried fish relish with okra',
    'Small dried fish with tomatoes and oil',
    'Small dried fish, fried',
    'Cheese, chedder',
    'Cheese, cream',
    'Cheese, mozarella',
    'Ice cream',
    'Infant formula, Lactogen',
    'Milk, condensed, sweetened',
    'Milk, condensed, evaported, without vitamin A',
    'Milk powder, non-fat, without vitamin A',
    'Milk powder, full-cream',
    'Milk whole, 3.25% milk fat',
    'Yogurt, plain, whole milk',
    'Butter refined-ghee',
    'Butter with salt',
    'Coconut cream',
    'Coconut meat, raw',
    'Coconut milk and water',
    'Coconut oil',
    'Coconut water',
    'Margarine',
    'Palm oil',
    'Sesame oil',
    'Vegetable fat',
    'Vegetable fat, Cowboy',
    'Vegetable fat, Kimbo',
    'Vegetable oil',
    'Apples, raw, with skin',
    'Avocado, raw, all common variety',
    'Banana, ripe',
    'Baobab, pulp',
    'Breadfruit, raw',
    'Custard-apple (bullock’s heart), raw',
    'Date, red, dried',
    'Date, yellow',
    'Durian',
    'Grape',
    'Grapefruit',
    'Grapes, pale green',
    'Guavas, common, raw',
    'Jackfruit, raw',
    'Lemon, raw, without peel',
    'Limes, raw',
    'Mango juice',
    'Mango, ripe, fresh-EP',
    'Mango, unripe',
    'Orange juice, concentrated, unsweetened',
    'Orange, raw-AP',
    'Papaya, ripe',
    'Papaya, unripe',
    'Passion, fruit',
    'Peach',
    'Pears, raw',
    'Pineapple juice',
    'Pineapple, raw, all variety',
    'Plums, raw',
    'Raspberry',
    'Soursop, raw',
    'Tamarind',
    'Tamarind, fruit, fresh',
    'Tangerines, raw',
    'Watermelon, raw',
    'Apple juice',
    'Avocado juice',
    'Grape juice',
    'Mixed fruit jam',
    'Mixed fruit juice',
    'Papaya juice',
    'Passion juice',
    'Watermelon juice',
    'Amaranth, leaves, raw',
    'Bean, cluster',
    'Bean, french',
    'Cabbage, chinese, raw',
    'Cabbage, cooked',
    'Cabbage, raw, green, white',
    'Carrot, juice',
    'Carrots, raw',
    'Cassava leaf',
    'Cauliflower, cooked without salt',
    'Cauliflower, raw',
    'Chili, green',
    'Cowpea leaf',
    'Cucumber, with peel, raw',
    'Egg plant, raw',
    'Green medium, leaf',
    'Green pepper (capsicum)',
    'Hare lettuce, (mchunga)',
    'Lettuce',
    'Mushroom',
    'Okra, raw',
    'Onion, raw',
    'Pea, green, fresh',
    'Pepper dried or fresh, hot',
    'Pumpkin leaf, raw',
    'Pumpkin, cooked',
    'Salad, green',
    'Spinach, cooked',
    'Sweet potato leaf',
    'Swiss chard, raw',
    'Taro leaf, raw',
    'Tomato, bitter (African egg plant)',
    'Tomato, green',
    'Tomato, ripe',
    'Cabbage relish with oil',
    'Cabbage, onion salad',
    'Cassava leaf relish with groundnuts',
    'Cassava leaf relish with coconut milk',
    'Cow pea leaf relish with coconut milk',
    'Cow pea leaf relish with groundnuts',
    'Egg plant relish',
    'Green leaf, medium, relish with coconut milk',
    'Green leaf, medium relish with groundnuts',
    'Green leaf, medium, relish without oil',
    'Green leaf, medium, relish with oil',
    'Green peas relish without oil',
    'Green peas relish with oil',
    'Green peas relish with oil and coconut milk',
    'Green peas relish with coconut milk',
    'Hare lettuce (mchunga)',
    'Okra relish without oil',
    'Okra relish with oil',
    'Okra relish with coconut milk',
    'Okra, fried',
    'Sweet potato leaf relish with coconut milk',
    'Potato leaf relish with milk',
    'Potato leaf relish with oil',
    'Potato samosa',
    'Pumpkin leaf relish without oil',
    'Pumpkin leaf relish with oil',
    'Spinach relish with groundnut and oil',
    'Spinach relish without oil',
    'Spinach relish with oil',
    'Spinach relish with sesame seeds',
    'Tomato relish',
    'Beer, commercial',
    'Beer, local, grain',
    'Beer, local, non-specific',
    'Blackcurrant, syrup, ribena',
    'Candy, choclate',
    'Carbonated, beverage, coca cola',
    'Chili powder, red',
    'Chili sauce',
    'Coconut immature, meat and water',
    'Cod liver oil',
    'Coffee, instant',
    'Cricket',
    'Fruit flavored drink, concentrated',
    'Garlic, fresh-AP',
    'Ginger',
    'Honey',
    'Ice sherbet',
    'Orange drink, concentrated',
    'Salt, iodized',
    'Salt,,non-iodized',
    'Soy sauce',
    'Soybean milk, dried',
    'Sugar',
    'Sugarcane',
    'Sugarcane juice',
    'Tea leaves',
    'Termite',
    'Tomato juice',
    'Tomato ketchup',
    'Tomato paste',
    'Vinegar, wine',
    'Coffee with milk, without sugar',
    'Coffee without milk, with sugar,',
    'Coffee with milk and sugar',
    'Groundnut cluster',
    'Halwa',
    'Tea with milk, without sugar',
    'Tea without milk, with sugar',
    'Tea with milk and sugar',
    'Beef broth without oil',
    'Beef broth with oil',
    'Cabbage broth without oil',
    'Cabbage broth with oil',
    'Cassava leaf broth without oil',
    'Cassava leaf broth with coconut milk',
    'Cassava leaf broth with oil',
    'Chicken broth without oil',
    'Chicken broth with oil',
    'Cow pea broth without oil',
    'Cow pea broth with coconut milk',
    'Cow pea broth with oil',
    'Cow pea leaf broth without oil',
    'Cow pea leaf broth with coconut milk',
    'Cow pea leaf broth with oil',
    'Fish broth without oil',
    'Fish broth with coconut milk',
    'Fish broth with oil',
    'Green pea broth without oil',
    'Green pea broth with coconut milk',
    'Green Pea Broth with oil',
    'Ground beef relish broth',
    'Kidney bean broth without oil',
    'Kidney bean broth with coconut milk',
    'Kidney bean broth with oil',
    'Liver relish broth',
    'Pumpkin leaf broth without oil',
    'Pumpkin leaf broth with oil',
    'Small dried fish broth with oil',
    'Spinach broth without oil',
    'Spinach broth with oil'
  ];

  static List<String> foodnames = [
    'Biscuit',
    'Bread roll',
    'Bread, white',
    'Cake',
    'Cookie',
    'Donut',
    'Infant cereal, Cerelac',
    'Macaroni or spaghetti',
    'Maize, cracked, cooked',
    'Maize, dried, raw',
    'Maize, flour, dry',
    'Maize, green, cooked',
    'Maize, on the cob, immature',
    'Maize, yellow, flour',
    'Millet, bulrush',
    'Millet, finger, grain or flour',
    'Mixed porridge flour (maize and oil)',
    'Mixed porridge flour (no maize)',
    'Mixed porridge flour (with maize)',
    'Porridge, fermented',
    'Rice, flour, local',
    'Rice, fried and boiled',
    'Rice, white, grain, raw',
    'Semolina',
    'Sorghum',
    'Sorghum, flour',
    'Vermicelli, uncooked',
    'Wheat, flour, whole grain',
    'Wheat,dough, deep fried',
    'Wheat, flour, 72% extract',
    'Wheat, flour, maida',
    'Cake (home made)',
    'Chapati, dry Indian',
    'Chapati with oil',
    'Donut-African',
    'Maize and kidney bean dish',
    'Maize and sorgum ugali (stiff porridge)',
    'Maize porridge with margarine and sugar',
    'Maize porridge no sugar no milk',
    'Maize porridge with sugar',
    'Maize porridge with sugar and egg',
    'Maize porridge with sugar and milk',
    'Maize ugali (stiff porridge)',
    'Millet porridge with sugar',
    'Mix flour porridge with sugar',
    'Pancake',
    'Rice biriyani',
    'Rice boiled no Oil',
    'Rice boiled with Oil',
    'Rice bread',
    'Rice bun',
    'Rice and meat pillau',
    'Rice and mung dish with coconut milk',
    'Rice and mung dish no coconut milk',
    'Rice poridge with coconut no sugar',
    'Rice porridge with sugar',
    'Rice ugali (stiff porridge)',
    'Rice with coconut milk',
    'Rice with ground meat',
    'Sorgum and millet ugali (stiff porridge)',
    '511   Sorgum porridge with sugar',
    'Vermicelli - cooked',
    'Vermicelli with coconut milk and sugar',
    'Vermicell with oil and sugar',
    'Vermicelli with coconut milk and salt',
    'Wheat fritter, sweet',
    'Wheat porridge',
    'Banana, cooked',
    'Breadfruit, raw',
    'Cassava, dried',
    'Cassava, dried, flour',
    'Cassava, raw',
    'Cassava, spicy crisps or chips',
    'Edible starch, tapioca or corn',
    'Potato, crisps, plain, salted',
    'Potato, English, cooked',
    'Potato, raw, with skin',
    'Squash, fresh-AP',
    'Squash, fresh-EP',
    'Sweet potato, fresh-AP',
    'Sweet potato, fresh-EP',
    'Sweet potato, orange',
    'Taro, raw',
    'Yam, raw',
    'Banana porridge, plain',
    'Banana porridge with meat',
    'Banana porridge with fish',
    'Banana porridge with meat and spinach',
    'Banana with cashew nut',
    'Banana with coconut milk',
    'Banana with kidney beans',
    'Banana with meat',
    'Banana with meat and coconut milk',
    'Banana with meat, oil and vegetable',
    'Banana with oil (no meat )',
    'Banana, boiled',
    'Banana, fried',
    'Banana, roast',
    'Cassava porridge with sugar',
    'Cassava stiff porridge',
    'Cassava with coconut milk',
    'Cassava, boiled',
    'Cassava, fried',
    'Kachori (spicy potato balls)',
    'Potato chips, fried',
    'Potato relish with beef',
    'Potato relish with coconut milk',
    'Potato relish with oil',
    'Potato, boiled',
    'Roots and tubers mixed',
    'Sweet potato, boiled',
    'Sweet potato, fried',
    'Taro, cooked, without salt',
    'Almonds',
    'Bambara groundnut, fresh',
    'Bean, kidney, green, cooked',
    'Bean, mung, dry',
    'Bean, mung, raw',
    'Beans, kidney, mature, boiled without salt',
    'Beans, kidney, mature seeds, raw',
    'Cashewnut',
    'Chickpea',
    'Chickpea flour (besan)',
    'Cowpea, green, uncooked',
    'Cowpea, uncooked',
    'Hyancinth beans (dried)',
    'Hyacinth-beans, immature, raw',
    'Hyacinth-beans, immature, boiled without salt',
    'Lentil, cooked',
    'Lentil, whole',
    'Palm seed',
    'Groundnuts',
    'Peanut butter, smooth',
    'Pigeon peas, cooked',
    'Pigeon peas, green',
    'Pigeon peas, raw',
    'Pumpkin seed',
    'Sesame seed',
    'Soybean, yellow',
    'Sunflower seed',
    'Bambara nut relish with coconut milk',
    'Bhajia (chickpea flour fritters)',
    'Chick pea relish with coconut milk',
    'Cow pea (dry) relish without oil',
    'Cow pea (dry) relish with oil',
    'Cow pea (fresh) relish without oil',
    'Cow pea relish with coconut milk',
    'Kidney bean relish without oil',
    'Kidney bean relish with oil',
    'Kidney bean relish with coconut milk',
    'Mung bean (dry) relish with cocount milk',
    'Mung bean (dry, boiled)',
    'Pigeon pea (fresh, cooked)',
    'Pigeon pea relish with coconut milk',
    'Pigeon pea relish with oil',
    'Beef liver, raw',
    'Beef, boneless',
    'Beef, liver, cooked',
    'Beef, medium fat, cooked',
    'Beef, tripe',
    'Chicken liver',
    'Chicken, raw',
    'Egg yolk',
    'Egg, chicken',
    'Fish, dried, cod',
    'Fish, dried, fresh water',
    'Fish, fresh',
    'Fish, high fat',
    'Fish, raw',
    'Fish, sardines',
    'Fish, small, dried, fresh water',
    'Fish, small, fresh, fresh water',
    'Fish, smoked, dried-AP',
    'Fish, smoked, dried-EP',
    'Goat meat',
    'Mutton, meat',
    'Pork, medium fat, cooked',
    'Sausage',
    'Beef relish with coconut milk',
    'Beef relish without oil',
    'Beef relish with oil',
    'Beef, fried',
    'Beef, ground, relish',
    'Chicken, boiled or roasted',
    'Chicken relish without oil',
    'Chicken relish with coconut milk',
    'Chicken relish with oil',
    'Chicken, fried',
    'Egg boiled',
    'Egg, fried',
    'Fish, fresh, stew',
    'Fish relish without oil',
    'Fish relish with coconut milk',
    'Fish relish with oil',
    'Fish, fried',
    'Fish, fried, relish',
    'Liver relish',
    'Liver, fried',
    'Meat samosa',
    'Meat, barbecued',
    'Omelet, spanish',
    'Omelet, spanish with potato',
    'Small dried fish relish with coconut milk ',
    'Small dried fish relish with okra',
    'Small dried fish with tomatoes and oil',
    'Small dried fish, fried',
    'Cheese, chedder',
    'Cheese, cream',
    'Cheese, mozarella',
    'Ice cream',
    'Infant formula, Lactogen',
    'Milk, condensed, sweetened',
    'Milk, condensed, evaported, without vitamin A',
    'Milk powder, non-fat, without vitamin A',
    'Milk powder, full-cream',
    'Milk whole, 3.25% milk fat',
    'Yogurt, plain, whole milk',
    'Butter refined-ghee',
    'Butter with salt',
    'Coconut cream',
    'Coconut meat, raw',
    'Coconut milk and water',
    'Coconut oil',
    'Coconut water',
    'Margarine',
    'Palm oil',
    'Sesame oil',
    'Vegetable fat',
    'Vegetable fat, Cowboy',
    'Vegetable fat, Kimbo',
    'Vegetable oil',
    'Apples, raw, with skin',
    'Avocado, raw, all common variety',
    'Banana, ripe',
    'Baobab, pulp',
    'Breadfruit, raw',
    'Custard-apple (bullock’s heart), raw',
    'Date, red, dried',
    'Date, yellow',
    'Durian',
    'Grape',
    'Grapefruit',
    'Grapes, pale green',
    'Guavas, common, raw',
    'Jackfruit, raw',
    'Lemon, raw, without peel',
    'Limes, raw',
    'Mango juice',
    'Mango, ripe, fresh-EP',
    'Mango, unripe',
    'Orange juice, concentrated, unsweetened',
    'Orange, raw-AP',
    'Papaya, ripe',
    'Papaya, unripe',
    'Passion, fruit',
    'Peach',
    'Pears, raw',
    'Pineapple juice',
    'Pineapple, raw, all variety',
    'Plums, raw',
    'Raspberry',
    'Soursop, raw',
    'Tamarind',
    'Tamarind, fruit, fresh',
    'Tangerines, raw',
    'Watermelon, raw',
    'Apple juice',
    'Avocado juice',
    'Grape juice',
    'Mixed fruit jam',
    'Mixed fruit juice',
    'Papaya juice',
    'Passion juice',
    'Watermelon juice',
    'Amaranth, leaves, raw',
    'Bean, cluster',
    'Bean, french',
    'Cabbage, chinese, raw',
    'Cabbage, cooked',
    'Cabbage, raw, green, white',
    'Carrot, juice',
    'Carrots, raw',
    'Cassava leaf',
    'Cauliflower, cooked without salt',
    'Cauliflower, raw',
    'Chili, green',
    'Cowpea leaf',
    'Cucumber, with peel, raw',
    'Egg plant, raw',
    'Green medium, leaf',
    'Green pepper (capsicum)',
    'Hare lettuce, (mchunga)',
    'Lettuce',
    'Mushroom',
    'Okra, raw',
    'Onion, raw',
    'Pea, green, fresh',
    'Pepper dried or fresh, hot',
    'Pumpkin leaf, raw',
    'Pumpkin, cooked',
    'Salad, green',
    'Spinach, cooked',
    'Sweet potato leaf',
    'Swiss chard, raw',
    'Taro leaf, raw',
    'Tomato, bitter (African egg plant)',
    'Tomato, green',
    'Tomato, ripe',
    'Cabbage relish with oil',
    'Cabbage, onion salad',
    'Cassava leaf relish with groundnuts',
    'Cassava leaf relish with coconut milk',
    'Cow pea leaf relish with coconut milk',
    'Cow pea leaf relish with groundnuts',
    'Egg plant relish',
    'Green leaf, medium, relish with coconut milk',
    'Green leaf, medium relish with groundnuts',
    'Green leaf, medium, relish without oil',
    'Green leaf, medium, relish with oil',
    'Green peas relish without oil',
    'Green peas relish with oil',
    'Green peas relish with oil and coconut milk',
    'Green peas relish with coconut milk',
    'Hare lettuce (mchunga)',
    'Okra relish without oil',
    'Okra relish with oil',
    'Okra relish with coconut milk',
    'Okra, fried',
    'Sweet potato leaf relish with coconut milk',
    'Potato leaf relish with milk',
    'Potato leaf relish with oil',
    'Potato samosa',
    'Pumpkin leaf relish without oil',
    'Pumpkin leaf relish with oil',
    'Spinach relish with groundnut and oil',
    'Spinach relish without oil',
    'Spinach relish with oil',
    'Spinach relish with sesame seeds',
    'Tomato relish',
    'Beer, commercial',
    'Beer, local, grain',
    'Beer, local, non-specific',
    'Blackcurrant, syrup, ribena',
    'Candy, choclate',
    'Carbonated, beverage, coca cola',
    'Chili powder, red',
    'Chili sauce',
    'Coconut immature, meat and water',
    'Cod liver oil',
    'Coffee, instant',
    'Cricket',
    'Fruit flavored drink, concentrated',
    'Garlic, fresh-AP',
    'Ginger',
    'Honey',
    'Ice sherbet',
    'Orange drink, concentrated',
    'Salt, iodized',
    'Salt,,non-iodized',
    'Soy sauce',
    'Soybean milk, dried',
    'Sugar',
    'Sugarcane',
    'Sugarcane juice',
    'Tea leaves',
    'Termite',
    'Tomato juice',
    'Tomato ketchup',
    'Tomato paste',
    'Vinegar, wine',
    'Coffee with milk, without sugar',
    'Coffee without milk, with sugar,',
    'Coffee with milk and sugar',
    'Groundnut cluster',
    'Halwa',
    'Tea with milk, without sugar',
    'Tea without milk, with sugar',
    'Tea with milk and sugar',
    'Beef broth without oil',
    'Beef broth with oil',
    'Cabbage broth without oil',
    'Cabbage broth with oil',
    'Cassava leaf broth without oil',
    'Cassava leaf broth with coconut milk',
    'Cassava leaf broth with oil',
    'Chicken broth without oil',
    'Chicken broth with oil',
    'Cow pea broth without oil',
    'Cow pea broth with coconut milk',
    'Cow pea broth with oil',
    'Cow pea leaf broth without oil',
    'Cow pea leaf broth with coconut milk',
    'Cow pea leaf broth with oil',
    'Fish broth without oil',
    'Fish broth with coconut milk',
    'Fish broth with oil',
    'Green pea broth without oil',
    'Green pea broth with coconut milk',
    'Green Pea Broth with oil',
    'Ground beef relish broth',
    'Kidney bean broth without oil',
    'Kidney bean broth with coconut milk',
    'Kidney bean broth with oil',
    'Liver relish broth',
    'Pumpkin leaf broth without oil',
    'Pumpkin leaf broth with oil',
    'Small dried fish broth with oil',
    'Spinach broth without oil',
    'Spinach broth with oil'
  ];

  List<String> getFoodList() {
    return foods;
  }
}
